name = "kontenmu-prod"
compatibility_date = "2024-05-29"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "PUCK_DATA"
id = "f7f73402ae7c4ea3bb380cf1b20ba759"

[[d1_databases]]
binding = "DB"
database_name = "KONTENMU_PROD_DB"
database_id = "fed8248d-2ba2-4d68-8430-b5f64ad2f6bc"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kontenmu-media"
