name = "kontenmu"
compatibility_date = "2024-05-29"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "PUCK_DATA"
id = "06af3dd1fcf24575a2b8057980d2cb2e"

[[d1_databases]]
binding = "DB"
database_name = "KONTENMU_DB"
database_id = "32b70d74-ed3d-4e0e-9d27-c5fb785cc374"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kontenmu-media"
