name = "kontenmu-prod"
compatibility_date = "2024-05-29"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "PUCK_DATA"
id = "84149d824f0f45ef9898b527c3d6b1e7"

[[d1_databases]]
binding = "DB"
database_name = "KONTENMU_PROD_DB"
database_id = "fb13bb27-0243-4e4b-bb2a-4df45e0dce41"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kontenmu-media"
